const express=require("express"); const catalog=require("../data/catalog"); let GoogleGenAI; try{({GoogleGenAI}=require("@google/genai"));}catch{} const router=express.Router();
const normalize=s=>String(s||"").toLowerCase();
const fallback=(message)=>{const q=normalize(message);const budget=(q.match(/(?:₹|rs\.?|inr)?\s*(\d{4,6})/)||[])[1];const max=budget?Number(budget):Infinity;let matches=catalog.filter(p=>p.price<=max&&p.availability==="in_stock"); if(q.includes("laptop"))matches=matches.filter(p=>p.category==="laptops");if(q.includes("gaming"))matches=matches.filter(p=>p.tags.includes("gaming"));if(q.includes("coding")||q.includes("program"))matches=matches.filter(p=>p.tags.includes("coding")||p.tags.includes("development"));if(q.includes("phone"))matches=matches.filter(p=>p.category==="smartphones"); if(!matches.length) matches=catalog.filter(p=>p.price<=max&&p.availability==="in_stock");return matches.slice(0,3);};
router.post("/chat",async(req,res)=>{try{const message=String(req.body.message||"").trim();if(!message)return res.status(400).json({error:"Message is required."});if(message.length>1000)return res.status(400).json({error:"Message is too long."});
const selected=fallback(message);let reply="";let productIds=selected.map(p=>p.product_id);let requirements={category:"",brand:"",purpose:"",budget:"",ram:"",processor:"",gpu:"",storage:""};
if(process.env.GEMINI_API_KEY&&GoogleGenAI){try{const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});const compact=catalog.map(p=>({id:p.product_id,name:p.name,category:p.category,price:p.price,attributes:p.attributes,tags:p.tags,stock:p.stock}));const prompt=`You are BuyZen's commerce recommendation agent. Use only this catalog: ${JSON.stringify(compact)}. Customer request: ${message}. Return JSON only with keys reply, productIds, requirements. Maximum 3 IDs. Never invent products/specs/prices. If no match use [] and extract requirements.`;const out=await ai.models.generateContent({model:process.env.GEMINI_MODEL||"gemini-2.5-flash",contents:prompt,config:{responseMimeType:"application/json"}});const parsed=JSON.parse(out.text.replace(/```json|```/g,"").trim());const valid=new Set(catalog.map(p=>p.product_id));productIds=(Array.isArray(parsed.productIds)?parsed.productIds:[]).map(String).filter(id=>valid.has(id)).slice(0,3);requirements={...requirements,...(parsed.requirements||{})};reply=String(parsed.reply||"");}catch(e){console.error("AI fallback:",e.message)}}
const products=productIds.map(id=>catalog.find(p=>p.product_id===id)).filter(Boolean);if(!reply)reply=products.length?`I found ${products.length} catalog-grounded option${products.length>1?"s":""}. I only recommend products currently available in BuyZen's catalog. Add one to your cart when you are ready; payment always requires your explicit confirmation.`:`I couldn't find a suitable product in the current catalog. I've captured your requirement for merchant demand insights.`;
const upsellIds=products.some(p=>p.category==="laptops")?["bz-mouse-001","bz-bag-001"]:[];res.json({reply,productIds,upsellIds,requirements});}catch(e){console.error(e);res.status(500).json({error:"The commerce agent could not complete the request."});}});
module.exports=router;
