import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { addAuditEvent } from "../utils/commerce";

const loadScript=()=>new Promise((resolve)=>{if(window.Razorpay)return resolve(true);const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s);});

function Checkout(){
 const navigate=useNavigate(); const [cart,setCart]=useState([]); const [customer,setCustomer]=useState({name:"",email:"",phone:"",address:"",city:"",pincode:""}); const [confirmed,setConfirmed]=useState(false); const [paying,setPaying]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("cart"))||[])}catch{}},[]);
 const subtotal=useMemo(()=>cart.reduce((s,i)=>s+Number(i.price||0)*Number(i.quantity||1),0),[cart]); const delivery=subtotal>=1000?0:50; const total=subtotal+delivery;
 const change=e=>setCustomer(c=>({...c,[e.target.name]:e.target.value}));
 const saveOrder=(payment)=>{const order={id:`BZ-${Date.now()}`,customer,items:cart,subtotal,delivery,total,paymentMethod:"Razorpay",paymentStatus:"Paid",orderStatus:"Confirmed",payment,date:new Date().toISOString()};const orders=JSON.parse(localStorage.getItem("orders")||"[]");localStorage.setItem("orders",JSON.stringify([order,...orders]));localStorage.removeItem("cart");navigate("/order-success",{state:{order}});};
 const pay=async(e)=>{e.preventDefault();setError("");if(!cart.length)return setError("Your cart is empty.");if(!confirmed)return setError("Please explicitly confirm the exact amount before payment."); if(!customer.name||!customer.email)return setError("Please provide at least your name and email.");
 setPaying(true);await addAuditEvent({action:"PAYMENT_CONFIRMED_BY_USER",details:{total,items:cart.map(i=>({id:i.id,quantity:i.quantity,price:i.price}))},money_action:true,user_confirmation:true});
 try{const orderRes=await fetch("/api/payments/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart.map(i=>({id:i.id,quantity:i.quantity,source:i.source||"catalog"})),delivery,customer:{name:customer.name,email:customer.email}})});const orderData=await orderRes.json();if(!orderRes.ok)throw new Error(orderData.error||"Could not create payment order");
 const ok=await loadScript();if(!ok)throw new Error("Razorpay Checkout could not be loaded. No order was fulfilled and your cart is preserved.");
 const options={key:orderData.keyId,amount:orderData.amount,currency:orderData.currency,name:"BuyZen",description:"AI-assisted commerce order",order_id:orderData.orderId,prefill:{name:customer.name,email:customer.email,contact:customer.phone},handler:async(response)=>{try{const verify=await fetch("/api/payments/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(response)});const verified=await verify.json();if(!verify.ok||!verified.verified)throw new Error(verified.error||"Payment verification failed");await addAuditEvent({action:"PAYMENT_VERIFIED",details:{orderId:response.razorpay_order_id,paymentId:response.razorpay_payment_id,total},money_action:true,outcome:"verified"});saveOrder({razorpayOrderId:response.razorpay_order_id,razorpayPaymentId:response.razorpay_payment_id});}catch(err){setError(`${err.message}. Payment was not treated as successful. Please contact support before retrying.`);await addAuditEvent({action:"PAYMENT_VERIFICATION_FAILURE",details:{message:err.message},money_action:true,outcome:"gracefully_handled"});}finally{setPaying(false);}},modal:{ondismiss:async()=>{setPaying(false);await addAuditEvent({action:"PAYMENT_CHECKOUT_DISMISSED",details:{total},money_action:true,outcome:"no_charge_assumed"});}},theme:{color:"#1a1814"}};
 new window.Razorpay(options).open();
 }catch(err){setError(err.message||"Payment could not be started. No order has been confirmed and your cart remains unchanged.");setPaying(false);await addAuditEvent({action:"PAYMENT_FAILURE",details:{message:err.message},money_action:true,outcome:"gracefully_handled"});}}
 return <div className="checkout-page"><h1>Secure AI-Gated Checkout</h1><p>BuyZen never charges you automatically. Review the exact amount and explicitly confirm before opening payment.</p><div className="checkout-container"><form className="checkout-form" onSubmit={pay}><h2>Customer details</h2>{["name","email","phone","address","city","pincode"].map(n=><input key={n} name={n} value={customer[n]} onChange={change} placeholder={n[0].toUpperCase()+n.slice(1)} required={n==="name"||n==="email"}/>) }<label className="payment-confirmation"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I confirm that I want to pay exactly ₹{total.toLocaleString("en-IN")} for the items shown.</label>{error&&<p className="payment-error">{error}</p>}<button className="place-order-btn" disabled={paying}>{paying?"Processing…":"Pay securely with Razorpay"}</button></form><div className="checkout-summary-box"><h2>Explainable payment summary</h2>{cart.map(i=><div className="summary-product" key={`${i.source}:${i.id}`}><span>{i.name} × {i.quantity}</span><strong>₹{(Number(i.price)*Number(i.quantity)).toLocaleString("en-IN")}</strong></div>)}<div className="summary-line"><span>Subtotal</span><span>₹{subtotal.toLocaleString("en-IN")}</span></div><div className="summary-line"><span>Delivery</span><span>{delivery?`₹${delivery}`:"FREE"}</span></div><hr/><div className="summary-total"><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><p>🔒 Payment verification happens on the server before the order is marked paid.</p></div></div></div>;
}
export default Checkout;
